import { CareerProps } from "../types/careers";

export const CAREERS: CareerProps[] = [
  {
    position: "Information Technology Specialist",
    company: "Divisi Profesi dan Pengamanan Mabes Polri",
    logo: null,
    location: "Jakarta, ID",
    location_type: "On Site",
    type: "Freelance",
    start_date: "2023-11",
    end_date: "2024-10",
    industry: "polri",
    link: "https://polri.go.id",
    responsibilities: [
      "Provided user support and training on how to effectively use the Propam Integrated System (PIS) applications",
      "Managed and maintained application systems, focusing on troubleshooting, performance optimization, and improvements to ensure smooth operation.",
      "Built the core backend and integrated APIs across the PIS system for monitoring purposes.",
      "Developed applications based on divisional regulations (Perkadiv) with customized business processes.",
      "Built full-stack web applications using the newest and most robust technologies for clients, with a particular focus on the front-end side.",
      "Deployed applications to servers running on Windows Server.",
      "Coordinated with cross-functional teams to gather requirements and ensure successful application development and deployment.",
      "Monitored and analyzed system performance to identify areas for improvement and implement necessary updates or patches.",
    ],
  },
  {
    position: "Full-stack Developer",
    company: "Telemetri BWS Maluku",
    logo: null,
    location: "Maluku, ID",
    location_type: "Remote",
    type: "Freelance",
    start_date: "2019-09",
    end_date: "2020-01",
    industry: "startup",
    link: "#",
    responsibilities: [
      "Designed and developed a website for the Telemetri BWS Maluku system to monitor environmental data.",
      "uilt both an admin dashboard and landing page for managing and displaying telemetry data.",
      "Utilized CodeIgniter 3 for back-end development, MySQL for database management, and Bootstrap for front-end design.",
    ],
  },
  {
    position: "Full-stack Developer",
    company: "Localhosts Social Community",
    logo: null,
    location: "Cianjur, ID",
    location_type: "Remote",
    type: "Freelance",
    start_date: "2019-04",
    end_date: "2019-08",
    industry: "startup",
    link: "#",
  },
  {
    position: "Web Developer",
    company: "Baramij Integrasi Teknologi",
    logo: null,
    location: "Bandung, ID",
    location_type: "Onsite",
    type: "Internship",
    start_date: "2019-03",
    end_date: "2019-08",
    industry: "startup",
    link: "https://www.baramijintegrasi.com",
    responsibilities: [
      "Completed an internship as a Full-stack Developer, contributing to the development of the GENRUS Nusantara Boarding School’s admin dashboard for managing financial needs.",
      "Worked with Laravel, CodeIgniter, MySQL, and Bootstrap to create efficient and user-friendly administrative tools.",
    ],
  },
];
